<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('member_model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('index.php/utsorder');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('utsorder');
		}
		else
		{
			$chek=$this->member_model->checkuser(
				$this->input->post('username'),
				$this->input->post('pass'));
			
			if (!empty($chek)) {
				$this->session->set_userdata('logined',true);
				$this->session->set_userdata('nama',$chek->username);
				redirect('index.php/utshome/order');
			}else{
				redirect("index.php/utshome/login");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('nama');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */