<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class loginAdmin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('admin_model');
    }

    public function index()
    {
		if($this->session->userdata('loginedAdmin') && $this->session->userdata('loginedAdmin') == true)
		{
			redirect('index.php/utshomeadmin');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('index.php/utshomeadmin.php');
		}
		else
		{
			$chek=$this->admin_model->checkAdmin(
				$this->input->post('username'),
				$this->input->post('pass'));
			
			if (!empty($chek)) {
				$this->session->set_userdata('loginedAdmin',true);
				$this->session->set_userdata('namaAdmin',$chek->nama);
				redirect('index.php/utshomeadmin/member');
			}else{
				redirect("index.php/utshomeadmin");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('loginedAdmin');
		$this->session->unset_userdata('namaAdmin');
		redirect("index.php/utshomeadmin");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */